import type { Metadata } from 'next'
import './globals.css'
import { NextIntlClientProvider } from 'next-intl'
import { defaultLocale } from '~/plugins/i18n'
import { cookies } from 'next/headers'
import { LOCALE_KEY, LOCALES } from '~/constants'
import { AppSupportLanguage } from '~/types'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export const dynamic = 'force-dynamic'
export default async function RootLayout({ children, params }: { children: React.ReactNode; params: { locale: AppSupportLanguage } }) {
  const cookieStore = await cookies()
  const cookieLocale = cookieStore.get(LOCALE_KEY)?.value as AppSupportLanguage
  const locale = (LOCALES.includes(params.locale) && params.locale) || (LOCALES.includes(cookieLocale || '') ? cookieLocale : defaultLocale)

  const messages = (await import(`~/plugins/i18n/${locale}.json`)).default
  return (
    <html lang={params.locale}>
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
