import { GoogleTagManager } from '@next/third-parties/google';
import type { Metadata } from 'next';

import '@/app/globals.css';
import { GuestLayout } from '@/components/layout/GuestLayout';
import { ThemeProvider } from '@/context/SettingTheme.context';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = (
  props: Readonly<{
    children: React.ReactNode;
  }>
) => {
  const gtmID = process.env.gtmID || '';
  return (
    <ThemeProvider>
      <html lang="en">
        <head>{gtmID ? <GoogleTagManager gtmId={gtmID} /> : null}</head>
        <GuestLayout>{props.children}</GuestLayout>
      </html>
    </ThemeProvider>
  );
};

export default RootLayout;
