import { GoogleTagManager } from '@next/third-parties/google';
import type { Metadata } from 'next';
import { ReactNode } from 'react';
import 'public/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = (
  props: Readonly<{
    children: ReactNode;
  }>
) => {
  const gtmID = process.env.gtmID || '';
  return (
    <html lang="en">
      <head>{gtmID ? <GoogleTagManager gtmId={gtmID} /> : null}</head>
      <body>{props.children}</body>
    </html>
  );
};

export default RootLayout;
